name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "wbb"
          replace: "EvaMariaRobot"
          regex: false
          commit_message: 'Aayush'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Mr-Dark-Prince
          commit_user_email: 73339924+Mr-Dark-Prince@users.noreply.github.com
          commit_author: Mr-Dark-Prince <73339924+Mr-Dark-Prince@users.noreply.github.com>
